### PR TITLE
Add a simple indexed search

### PR DESCRIPTION
**Pull request by Mark-H**
Obviously needs work on the code to make it suitable to run, it's a mess currently.

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Could you, by chance, merge this? We could call master "dev" for the time being, and do most of our development in there. There are already some merge conflicts, and if I feel refactoring code, I think it will be a lot of them very soon.

**Comment by Mark-H** [comment]
I'm still a little conflicted (pun totally intended) if I want search implemented this way, with this tool. 

The readme made the search sound better than it really is and even for very specific terms, it was not quite giving me the results I was hoping for while testing. Then I wanted to try and index things a little differently, only to find out I had already exhausted the functionality this particular search library offers. :/ 

Something like Elastic would be great but I'm not looking forward to having to set up and manage that infrastructure so I was quite excited for a native php indexed search.

**Comment by OptimusCrime** [comment]
Using docker, loading up Elastic would be very easy. But I get your point.

**Comment by Mark-H** [comment]
Yeah, my problem is just that don't want to put docker in production... there are lots of warning signs when you look that up that tell you to know what you're doing (especially if there are databases involved) and I've barely done anything with it, so I'm not experienced enough to debug that if shit hits the proverbial fan. 

If this were a side project nobody is going to really depend on I wouldn't care as much and give it a go, but this seems a little more important and I do get the impression that what we're building here now will end up in some form of production usage.

**Comment by Mark-H** [comment]
Since replaced with #15

**Pull request closed without merging**
