### PR TITLE
Responsive font sizes

### PR DESCRIPTION
**Pull request by JoshuaLuckers**
This is a work in progress to make font sizes responsive. For more info see: [RFS](https://github.com/twbs/rfs/)

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
I made a small start. It would be good if all the font-sizes are defined as variables and/or map.

**Comment by Ibochkarev** [comment]
@JoshuaLuckers please fix conflicts

**Comment by JoshuaLuckers** [comment]
Done 👍

**Comment by christianseel** [comment]
For headings it's also part in https://github.com/modxorg/DocsApp/pull/40

**Pull request closed without merging**
